### PR TITLE
ci: automatically build RPMs using Packit

### PR DESCRIPTION
**Pull request by praiskup**

### CODE REVIEW

**Comment by praiskup** [comment]
For the RPM builds to work (before we merge) admins need to get the [Packit service integrated](https://packit.dev/docs/guide#how-to-set-up-packit-on-github).

**Comment by lubomir** [comment]
I'd love to have this :heart_eyes: 

@ralphbean , can you help either add the packit service, or grant me enough permissions to be able to do it myself?

**Comment by praiskup** [comment]
May I help with moving this forward?

**Comment by lubomir** [comment]
@praiskup , the packit integration should now be enabled. Can you please rebase this on latest main and update the version in spec file to 0.8.1?

**Comment by praiskup** [comment]
Ralf still needs to approve here: https://github.com/packit/notifications/issues/622

**Pull request merged**
